---

- name: 'Include OS-specific variables'
  ansible.builtin.include_vars: '{{ ansible_os_family }}.yml'

- name: 'Setup/install tasks'
  ansible.builtin.include_tasks: 'setup-{{ ansible_os_family }}.yml'

- name: 'Ensure directories to export exist'
  ansible.builtin.file:
    path: '{{ item }}'
    state: 'directory'
    mode: '777'
  with_items: '{{ nfs_exports | map("split") | map("first") | unique }}'

- name: 'Copy exports file'
  ansible.builtin.template:
    src: 'exports.j2'
    dest: '/etc/exports'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'Reload nfs'

- name: 'Ensure nfs is running'
  ansible.builtin.service:
    name: '{{ nfs_server_daemon }}'
    state: 'started'
    enabled: 'yes'
  when: nfs_exports|length
