---

- name: 'Setting package facts'
  ansible.builtin.set_fact: 
    nfs_package_name: 
      - 'nfs-common'
      - 'nfs-kernel-server'
  when: not nfs_package_name

- name: 'Ensure NFS utilities are installed'
  ansible.builtin.apt:
    name: '{{ nfs_package_name }}'
    state: 'present'
