---
role_name_check: 1
dependency:
  name: galaxy
  options:
    ignore-errors: true

driver:
  name: 'docker'

platforms:
  - name: 'instance'
    image: 'lacrif/${MOLECULE_DISTRO_NAME:-debian}-systemd:${MOLECULE_DISTRO_VERSION:-bookworm}'
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
    cgroupns_mode: 'host'
    privileged: true
    pre_build_image: true

provisioner:
  name: 'ansible'
